services:

    nginx:
        image: nginx:latest
        working_dir: /App
        container_name: nginx
        volumes:
            - '.:/App'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: .
        working_dir: /App
        container_name: php-fpm
        volumes:
            - '.:/App'
            - /var/www/html/vendor